AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Team:
    Type: String
  Environment:
    Type: String
  Domain:
    Type: String
  Channel:
    Type: String
  Workspace:
    Type: String

Resources:
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Tags:
        - Key: Domain
          Value: ""
        - Key: Team
          Value: ""
      TopicName: "Demo_Notification"

  SlackBot:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties:
      ConfigurationName: 
        Fn::Sub: ${Team}-${Environment}-${Domain}
      IamRoleArn: 
        Fn::Sub:
        - 'arn:aws:iam::${AWS::AccountId}:role/${RoleName}'
        - RoleName: 
            Ref: SlackBotRole
      SlackChannelId: 
        Ref: Channel
      SlackWorkspaceId: 
        Ref: Workspace
      SnsTopicArns: 
        - Ref: NotificationTopic

  SlackBotRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: chatbot.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: Events
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "events:*"
                Resource:
                  - "*"